### ISSUE TITLE
The preview does not work

### ISSUE THREAD

**Issue by aborruso** [cmarquardt/quarto-simple-article#1]
Hi opening  https://cmarquardt.github.io/quarto-simple-article/ I have 404

Thank you

**Comment by cmarquardt** [comment]
Oops - that's true. My apologies! I hadn't yet come to setting up GitHub pages...

Could you try again? The pdf you should see contains two different versions of the rendered `template.qmd`- the first three pages are the one-column version using standard fonts at 10 pt (the default font size):

```yaml
format:
  simple-article-pdf:
    indent: false
    classoption: 
     - twoside
```

On the other hand, the last two pages are the output from the configuration as contained in the repository (i.e. two-column, a smaller font size (9pt) and using [TUG's non-free Lucida fonts](https://tug.org/store/lucida/index.html)):

```yaml
format:
  simple-article-pdf:
    indent: false
    classoption: 
     - 9pt
     - lucida
     - twocolumn
     - twoside
```
